### PR TITLE
Create PLAN.md

### PR DESCRIPTION
**Pull request by Wulf**

### CODE REVIEW

**Comment by Wulf** [comment]
Battles can occur because of bandits, thiefs, etc

**Comment by ashes999** [comment]
Why a file? There's already an issue here: https://github.com/deengames-prototypes/a-day-and-a-night-v3/issues/1

**Comment by Wulf** [comment]
I couldn't edit your post, and this helps identify changes on each revision.

**Comment by ashes999** [comment]
You're a collaborator now.

Please add your comment about battles to the main thing somewhere.

**Pull request closed without merging**
