### PR TITLE
Added Scene_Deeds and Summary window in main menu

### PR DESCRIPTION
**Pull request by Wulf**
## #It'sNeverTooLate

capture 1

capture 2

### CODE REVIEW

**Comment by ashes999** [comment]
You never cease to amaze me :) 

Can I request a few tiny changes:
- Get rid of that empty space in the main menu, if possible)
- The small panel with "deeds" and the subtotals: could you please change it from `Deeds` to `Deeds Summary:"?
- The "Deeds" item in the main menu (above Achievements): could you change it to `Accountability` or `Muhasaba` (whatever fits)?

Barakallahu feekum!

**Comment by Wulf** [comment]
capture 1
capture 2

**Comment by ashes999** [comment]
Sorry, two more things (I wasn't thinking clearly and I'm still not :()

All the points are going to be either +1 or -1. So instead of showing it, can you just make the item itself red or (anything but green for people who are red/green blind)? Yellow or blue may work. Use your judgement inshaAllah.

Can you also change "Deeds Summary" back to "Deeds"?

**Comment by ashes999** [comment]
@Wulf is this doable?

**Comment by Wulf** [comment]
Jeah hombre. T'is getting done. Busy right now though!

**Comment by ashes999** [comment]
Ok thanks.

**Comment by ashes999** [comment]
I'm in a hurry and did this myself (the last changed I asked for). It was pretty easy to grep and mangle your code. Thanks again!

**Pull request merged**
